apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  nginx.conf: |
    worker_processes 5;

    events {
    }

    http {
      # Certs for all SSL server_names.
      ssl_certificate     /certs/tls.crt;
      ssl_certificate_key /certs/tls.key;
      ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;

      # Sillier vanity domain we don't really do anything with.
      server {
        server_name ~^(.*\.)?kates\.io$;
        server_name kates.io;
        listen 80;
        listen 443 ssl;

        location /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }

        location / {
          return 301 https://$1k8s.io$request_uri;
        }
      }
    }
